#!/usr/bin/env python3
"""
Fix vocab KPs in a1.json and a2.json:
  1. Remove garbage artifact KPs from the Goethe PDF import.
  2. For every KP where english= contains a German example sentence,
     move that sentence to example_sentence and set the proper English translation.
"""

import json, re, sys, os

# ── KP IDs to delete entirely ────────────────────────────────────────────────
REMOVE_IDS = {
    # A1 – plain garbage / document metadata / sentence fragments
    'a1-vocab-numbers-kp-gemeinsamen', 'a1-vocab-numbers-kp-gemeinsamer',
    'a1-vocab-numbers-kp-sie',
    'a1-vocab-food-kp-chen', 'a1-vocab-food-kp-eine', 'a1-vocab-food-kp-meine',
    'a1-vocab-routines-kp-sche', 'a1-vocab-routines-kp-schen',
    'a1-vocab-home-kp-hin', 'a1-vocab-months-kp-die',
    'a1-vocab-shopping-kp-europ-ischen', 'a1-vocab-shopping-kp-den',
    'a1-vocab-travel-kp-alte',
    # A2 – plain garbage / document metadata / sentence fragments
    'a2-vocab-health-kp-alle',
    'a2-vocab-work-kp-bearbeiten', 'a2-vocab-work-kp-geh',
    'a2-vocab-work-kp-wer', 'a2-vocab-work-kp-vorstellen',
    'a2-vocab-education-kp-mitsch-ler', 'a2-vocab-education-kp-deutschpr-fung',
    'a2-vocab-education-kp-aufgabe', 'a2-vocab-education-kp-studenten',
    'a2-vocab-education-kp-sch-lerin',
    'a2-vocab-services-kp-werk', 'a2-vocab-services-kp-postleit',
    'a2-vocab-services-kp-sich',
    'a2-vocab-weather-kp-anweisungssprache', 'a2-vocab-weather-kp-beispielsweise',
    'a2-vocab-weather-kp-hinweis', 'a2-vocab-weather-kp-preise',
    'a2-vocab-weather-kp-reisef-hrer',
    'a2-vocab-clothing-kp-pass', 'a2-vocab-clothing-kp-lichtschalter',
    'a2-vocab-clothing-kp-zug', 'a2-vocab-clothing-kp-t-shirt',
    'a2-vocab-clothing-kp-tasche',
    'a2-vocab-emotions-kp-eine', 'a2-vocab-emotions-kp-einen',
    'a2-vocab-emotions-kp-liebe', 'a2-vocab-emotions-kp-rgern',
    'a2-vocab-emotions-kp-rgern--sich--2', 'a2-vocab-emotions-kp-verlieben',
    'a2-vocab-emotions-kp-gl-ck', 'a2-vocab-emotions-kp-wein',
    'a2-vocab-directions-kp-hin', 'a2-vocab-directions-kp-en',
    'a2-vocab-directions-kp-rechtslage',
    'a2-vocab-entertainment-kp-nachricht---en-2',
}

# ── English overrides keyed by KP ID ─────────────────────────────────────────
# Format: kp_id → (english_translation, clean_example_sentence | None)
# None  →  use the existing english field value as example_sentence (after cleanup)
EN = {}

def e(kp_id, translation, example=None):
    EN[kp_id] = (translation, example)

# ─── A1 vocab-numbers ────────────────────────────────────────────────────────
e('a1-vocab-numbers-kp-achtung',    'caution / watch out!')
e('a1-vocab-numbers-kp-aus',        'from / out of')
e('a1-vocab-numbers-kp-bezahlen',   'to pay')
e('a1-vocab-numbers-kp-l',          'oil',          'Den Salat machen wir ohne Öl.')
e('a1-vocab-numbers-kp-hund',       'dog')
e('a1-vocab-numbers-kp-nummer',     'number',       'Sie haben Zimmer Nummer zwölf.')
e('a1-vocab-numbers-kp-nummer---n-1','number / room number', 'Sie haben Zimmer Nummer zwölf.')
e('a1-vocab-numbers-kp-nummer---n-2','house number', 'Welche Hausnummer haben Sie?')
e('a1-vocab-numbers-kp-nummer---n-3','phone number', 'Können Sie mir Ihre Nummer geben?')
e('a1-vocab-numbers-kp-post',       'post office / mail')
e('a1-vocab-numbers-kp-postleitzahl','postal code / ZIP code')
e('a1-vocab-numbers-kp-einsteigen', 'to get on / to board')
e('a1-vocab-numbers-kp-helfen',     'to help')
e('a1-vocab-numbers-kp-neu',        'new')
e('a1-vocab-numbers-kp-und',        'and')
e('a1-vocab-numbers-kp-vier',       'four',         'Grad über Null/plus vier Grad = + 4°')
e('a1-vocab-numbers-kp-bernachten', 'to stay overnight')
# ─── A1 vocab-family ─────────────────────────────────────────────────────────
e('a1-vocab-family-kp-automatisch', 'automatic / automatically')
e('a1-vocab-family-kp-baby',        'baby')
e('a1-vocab-family-kp-baby---s',    'baby')
e('a1-vocab-family-kp-kind---er',   'child')
e('a1-vocab-family-kp-automat',     'vending machine / machine / ATM')
e('a1-vocab-family-kp-familienname','surname / last name')
e('a1-vocab-family-kp-familienstand','marital status')
e('a1-vocab-family-kp-hausmann',    'stay-at-home dad / househusband',
  'Die Hausfrau/der Hausmann wäscht, kocht und kauft ein.')
e('a1-vocab-family-kp-kindergarten','kindergarten / preschool')
e('a1-vocab-family-kp-mann------er','man / husband')
e('a1-vocab-family-kp-opa',         'grandpa / grandfather')
e('a1-vocab-family-kp-opa---s',     'grandpa / grandfather')
e('a1-vocab-family-kp-sohn------e', 'son')
e('a1-vocab-family-kp-ehefrau---en-der-ehemann------',
  'wife / husband',               'Das ist mein (Ehe-)Mann / meine (Ehe-)Frau.')
e('a1-vocab-family-kp-eltern--pl',  'parents')
e('a1-vocab-family-kp-familie',     'family')
e('a1-vocab-family-kp-familie---n', 'family')
e('a1-vocab-family-kp-frau---en-2', 'Mrs. / Ms. (title)',
  'Guten Tag, Frau Schmitt!')
e('a1-vocab-family-kp-frau---en-3', 'woman',
  'Hier arbeiten mehr Frauen als Männer.')
e('a1-vocab-family-kp-geschwister', 'siblings',
  'Ich habe leider keine Geschwister.')
e('a1-vocab-family-kp-geschwister--pl','siblings',
  'Ich habe leider keine Geschwister.')
e('a1-vocab-family-kp-gro-eltern',  'grandparents',
  'Meine Großeltern leben in Japan.')
e('a1-vocab-family-kp-gro-eltern--pl','grandparents',
  'Meine Großeltern leben in Japan.')
e('a1-vocab-family-kp-hausfrau---en-der-hausmann',
  'housewife / stay-at-home dad',
  'Die Hausfrau/der Hausmann wäscht, kocht und kauft ein.')
e('a1-vocab-family-kp-oma',         'grandma / grandmother')
e('a1-vocab-family-kp-oma---s',     'grandma / grandmother')
e('a1-vocab-family-kp-schwester---n','sister')
e('a1-vocab-family-kp-tochter',     'daughter')
e('a1-vocab-family-kp-tomate',      'tomato')
e('a1-vocab-family-kp-tomate---n',  'tomato')
e('a1-vocab-family-kp-gro',         'big / tall / large')
e('a1-vocab-family-kp-man',         'one / you (impersonal)')
# ─── A1 vocab-food (large) ───────────────────────────────────────────────────
e('a1-vocab-food-kp-an-sein',       'to be on / switched on')
e('a1-vocab-food-kp-arbeitslos',    'unemployed')
e('a1-vocab-food-kp-auf-sein',      'to be open',   'Die Wohnung ist auf.')
e('a1-vocab-food-kp-aussteigen',    'to get off / to exit')
e('a1-vocab-food-kp-bei',           'near / at / with (preposition)')
e('a1-vocab-food-kp-bei-1',         'near (location)',     'Offenbach liegt bei Frankfurt.')
e('a1-vocab-food-kp-bei-2',         'with / at (someone\'s home)', 'Ich wohne bei meinen Eltern.')
e('a1-vocab-food-kp-bei-3',         'at our place / in our area',  'Bei uns regnet es heute.')
e('a1-vocab-food-kp-bei-4',         'for / at (employer)', 'Er arbeitet bei der Polizei.')
e('a1-vocab-food-kp-beide',         'both')
e('a1-vocab-food-kp-bleiben',       'to stay / to remain')
e('a1-vocab-food-kp-bleiben-1',     'to stay (at home)',   'Ich bleibe heute zu Hause.')
e('a1-vocab-food-kp-bleiben-2',     'to stay (only until)', 'Wir bleiben nur bis morgen.')
e('a1-vocab-food-kp-breit',         'wide / broad')
e('a1-vocab-food-kp-buchstabieren', 'to spell out')
e('a1-vocab-food-kp-bein',          'leg')
e('a1-vocab-food-kp-bein---e',      'leg')
e('a1-vocab-food-kp-beispiel---e',  'example')
e('a1-vocab-food-kp-brot---e-1',    'bread (loaf)')
e('a1-vocab-food-kp-brot---e-2',    'bread rolls / loaves for a trip', 'Nimm noch ein paar Brote für die Fahrt mit.')
e('a1-vocab-food-kp-ei---er',       'egg')
e('a1-vocab-food-kp-einzelzimmer',  'single room')
e('a1-vocab-food-kp-getr-nk',       'drink / beverage')
e('a1-vocab-food-kp-getr-nk---e',   'drink / beverage')
e('a1-vocab-food-kp-gleis',         'platform / track (train)')
e('a1-vocab-food-kp-gleis---e',     'platform / track (train)')
e('a1-vocab-food-kp-h-hnchen',      'chicken (dish)')
e('a1-vocab-food-kp-reiseb-ro',     'travel agency')
e('a1-vocab-food-kp-reiseb-ro---s', 'travel agency')
e('a1-vocab-food-kp-restaurant',    'restaurant')
e('a1-vocab-food-kp-restaurant---s','restaurant')
e('a1-vocab-food-kp-salz',          'salt')
e('a1-vocab-food-kp-arbeitsplatz------e', 'workplace / workstation')
e('a1-vocab-food-kp-ausweis',       'ID card / identity card')
e('a1-vocab-food-kp-bahnsteig',     'platform (train station)')
e('a1-vocab-food-kp-bleistift',     'pencil')
e('a1-vocab-food-kp-bleistift---e', 'pencil')
e('a1-vocab-food-kp-durst',         'thirst')
e('a1-vocab-food-kp-eingang',       'entrance')
e('a1-vocab-food-kp-eintritt',      'admission / entry fee')
e('a1-vocab-food-kp-fisch',         'fish')
e('a1-vocab-food-kp-fisch---e',     'fish')
e('a1-vocab-food-kp-hunger',        'hunger')
e('a1-vocab-food-kp-kugelschreiber','ballpoint pen / pen')
e('a1-vocab-food-kp-preis',         'price')
e('a1-vocab-food-kp-preis---e',     'price')
e('a1-vocab-food-kp-reisef-hrer',   'travel guide (book)',  'Ich kaufe mir einen Reiseführer von Berlin.')
e('a1-vocab-food-kp-reisef-hrer-1', 'travel guide (book)',  'Ich kaufe mir einen Reiseführer von Berlin.')
e('a1-vocab-food-kp-reisef-hrer-2', 'tour guide (person)',  'Unser Reiseführer heißt Peter.')
e('a1-vocab-food-kp-saft',          'juice')
e('a1-vocab-food-kp-teil',          'part / piece')
e('a1-vocab-food-kp-teil---e',      'part / piece')
e('a1-vocab-food-kp-verein',        'club / association')
e('a1-vocab-food-kp-wein',          'wine')
e('a1-vocab-food-kp-anzeige',       'advertisement / notice')
e('a1-vocab-food-kp-anzeige---n',   'advertisement / notice')
e('a1-vocab-food-kp-arbeit',        'work / job')
e('a1-vocab-food-kp-arbeit---en',   'work / job')
e('a1-vocab-food-kp-butter',        'butter')
e('a1-vocab-food-kp-b-ckerei',      'bakery')
e('a1-vocab-food-kp-einladung',     'invitation')
e('a1-vocab-food-kp-freizeit',      'free time / leisure time')
e('a1-vocab-food-kp-heimat',        'home / homeland')
e('a1-vocab-food-kp-hochzeit',      'wedding')
e('a1-vocab-food-kp-kartoffel',     'potato')
e('a1-vocab-food-kp-kartoffel---n', 'potato')
e('a1-vocab-food-kp-kleidung',      'clothing / clothes')
e('a1-vocab-food-kp-polizei',       'police')
e('a1-vocab-food-kp-reise',         'trip / journey / travel')
e('a1-vocab-food-kp-sehensw-rdigkeit---en', 'sight / tourist attraction')
e('a1-vocab-food-kp-speisekarte',   'menu')
e('a1-vocab-food-kp-zeit',          'time')
e('a1-vocab-food-kp-zeitung',       'newspaper')
e('a1-vocab-food-kp-zeitung---en',  'newspaper')
e('a1-vocab-food-kp-ein',           'one / a (numeral / pronoun form)')
e('a1-vocab-food-kp-ein--1',        'one (pronoun)',  'Ich nehme ein Bier. Willst du auch eins?')
e('a1-vocab-food-kp-ein--2',        'one (someone)',  'Ist hier einer, der das kann?')
e('a1-vocab-food-kp-einfach',       'simple / easy')
e('a1-vocab-food-kp-einfach-1',     'simple / easy',  'Die Prüfung ist ganz einfach.')
e('a1-vocab-food-kp-einfach-2',     'one-way (travel)', 'Hin und zurück? – Nein, bitte nur einfach.')
e('a1-vocab-food-kp-einfach-3',     'basic / simple (room)', 'Ich brauche nur ein einfaches Zimmer.')
e('a1-vocab-food-kp-einkaufen',     'to shop / to go shopping')
e('a1-vocab-food-kp-einladen',      'to invite')
e('a1-vocab-food-kp-einmal',        'once / one time')
e('a1-vocab-food-kp-feier--2',      'holiday (compound prefix)', 'Am Montag ist Feiertag.')
e('a1-vocab-food-kp-feiern',        'to celebrate')
e('a1-vocab-food-kp-frei',          'free / available / vacant')
e('a1-vocab-food-kp-gleich-2',      'same / equal',   'Das ist der gleiche Preis.')
e('a1-vocab-food-kp-heiraten',      'to get married')
e('a1-vocab-food-kp-hei-en',        'to be called / to be named')
e('a1-vocab-food-kp-hei-en-1',      'to be called (name)', 'Ich heiße Charlotte Meier.')
e('a1-vocab-food-kp-hei-en-2',      'to be called (word)',  'Wie heißt das auf Deutsch?')
e('a1-vocab-food-kp-kein',          'no / not a / none')
e('a1-vocab-food-kp-klein',         'small / little')
e('a1-vocab-food-kp-leicht',        'light / easy')
e('a1-vocab-food-kp-leicht-1',      'light (weight)',  'Der Koffer ist leicht.')
e('a1-vocab-food-kp-leicht-2',      'easy (not hard)', 'Deutsch ist nicht leicht.')
e('a1-vocab-food-kp-leider',        'unfortunately')
e('a1-vocab-food-kp-leise',         'quiet / quietly / softly')
e('a1-vocab-food-kp-meist',         'most (prefix: mostly, most people)')
e('a1-vocab-food-kp-schreiben',     'to write')
e('a1-vocab-food-kp-sein',          'to be')
e('a1-vocab-food-kp-sein-1',        'to be (location)',  'Herr Müller ist in seinem Zimmer.')
e('a1-vocab-food-kp-sein-3',        'to be (age)',       'Ich bin dreiundzwanzig.')
e('a1-vocab-food-kp-seit',          'since / for (time period)')
e('a1-vocab-food-kp-unterschreiben','to sign')
e('a1-vocab-food-kp-verheiratet',   'married')
e('a1-vocab-food-kp-vielleicht',    'maybe / perhaps')
e('a1-vocab-food-kp-was-f-r-ein',   'what kind of / what sort of')
e('a1-vocab-food-kp-weg-sein',      'to be gone / to have left')
e('a1-vocab-food-kp-weiblich',      'female / feminine')
e('a1-vocab-food-kp-weit',          'far / wide')
e('a1-vocab-food-kp-weiter',        'further / to continue')
e('a1-vocab-food-kp-zu-sein',       'to be closed')
e('a1-vocab-food-kp-zum-beispiel-z--b', 'for example / e.g.')
e('a1-vocab-food-kp-zurzeit',       'currently / at the moment')
e('a1-vocab-food-kp-berweisen',     'to transfer (money)')
# ─── A1 vocab-daily-routines ─────────────────────────────────────────────────
e('a1-vocab-routines-kp-sich--anziehen', 'to put on / to get dressed')
e('a1-vocab-routines-kp-sich--ausziehen','to take off / to get undressed')
e('a1-vocab-routines-kp-sich--duschen',  'to shower')
e('a1-vocab-routines-kp-sich--waschen-1','to wash (hands)',  'Wo kann ich mir die Hände waschen?')
e('a1-vocab-routines-kp-sich--waschen-2','to do the washing', 'Ich muss morgen waschen.')
e('a1-vocab-routines-kp-anfangen',  'to start / to begin')
e('a1-vocab-routines-kp-anfangen-1','to start (location)',  'Hier fängt die Bahnhofstraße an.')
e('a1-vocab-routines-kp-anfangen-2','to start (class)',     'Der Unterricht fängt gleich an.')
e('a1-vocab-routines-kp-aufh-ren',  'to stop / to finish')
e('a1-vocab-routines-kp-aufstehen-1','to get up / to get out of bed')
e('a1-vocab-routines-kp-beginnen',  'to begin / to start')
e('a1-vocab-routines-kp-fr-hst-ck', 'breakfast')
e('a1-vocab-routines-kp-anfang',    'beginning / start')
e('a1-vocab-routines-kp-dusche',    'shower')
e('a1-vocab-routines-kp-h-ren',     'to hear / to listen')
e('a1-vocab-routines-kp-kaufen',    'to buy')
e('a1-vocab-routines-kp-stehen',    'to stand / to be written (text)')
# ─── A1 vocab-home ───────────────────────────────────────────────────────────
e('a1-vocab-home-kp-bad',           'bathroom / bath')
e('a1-vocab-home-kp-bett---en',     'bed')
e('a1-vocab-home-kp-doppelzimmer',  'double room')
e('a1-vocab-home-kp-haus------er-1','house',         'In welchem Haus wohnst du?')
e('a1-vocab-home-kp-haus------er-2','home (after nach Hause)', 'Ich gehe jetzt nach Hause.')
e('a1-vocab-home-kp-haus------er-3','at home (zu Hause)',      'Paul ist nicht zu Hause.')
e('a1-vocab-home-kp-zimmer-1',      'room (size)',   'Das Zimmer ist groß.')
e('a1-vocab-home-kp-zimmer-2',      'room (bedroom)','Öffne im Schlafzimmer das Fenster, bitte!')
e('a1-vocab-home-kp-zimmer-3',      'room (apartment size)', 'Die Wohnung hat drei Zimmer.')
e('a1-vocab-home-kp-zimmer-4',      'room (hotel)',  'Ich habe ein Zimmer bestellt.')
e('a1-vocab-home-kp-balkon',        'balcony')
e('a1-vocab-home-kp-garten',        'garden')
e('a1-vocab-home-kp-herd',          'stove / cooker')
e('a1-vocab-home-kp-k-hlschrank',   'refrigerator / fridge')
e('a1-vocab-home-kp-schl-ssel',     'key')
e('a1-vocab-home-kp-schrank------e','cupboard / wardrobe / cabinet')
e('a1-vocab-home-kp-stock',         'floor / storey (of a building)')
e('a1-vocab-home-kp-tisch---e',     'table')
e('a1-vocab-home-kp-vermieter',     'landlord')
e('a1-vocab-home-kp-hausaufgabe',   'homework')
e('a1-vocab-home-kp-hausaufgabe---n','homework')
e('a1-vocab-home-kp-maschine',      'machine / appliance')
e('a1-vocab-home-kp-miete',         'rent')
e('a1-vocab-home-kp-m-bel',         'furniture',     'Sind die Möbel neu?')
e('a1-vocab-home-kp-m-bel--pl',     'furniture')
e('a1-vocab-home-kp-toilette',      'toilet / restroom')
e('a1-vocab-home-kp-toilette---en', 'toilet / restroom')
e('a1-vocab-home-kp-treppe',        'stairs / staircase')
e('a1-vocab-home-kp-treppe---n',    'stairs / staircase')
e('a1-vocab-home-kp-wohnung---en',  'apartment / flat')
e('a1-vocab-home-kp-immer',         'always')
e('a1-vocab-home-kp-mieten',        'to rent')
e('a1-vocab-home-kp-vermieten',     'to rent out')
e('a1-vocab-home-kp-vor',           'before / ago / in front of')
# ─── A1 vocab-travel ─────────────────────────────────────────────────────────
e('a1-vocab-travel-kp-abfahren',    'to depart / to leave')
e('a1-vocab-travel-kp-ankommen',    'to arrive')
e('a1-vocab-travel-kp-auto---s',    'car')
e('a1-vocab-travel-kp-fahrrad------er','bicycle / bike')
e('a1-vocab-travel-kp-gep-ck',      'luggage / baggage')
e('a1-vocab-travel-kp-hotel',       'hotel')
e('a1-vocab-travel-kp-hotel---s',   'hotel')
e('a1-vocab-travel-kp-taxi',        'taxi')
e('a1-vocab-travel-kp-taxi---s',    'taxi')
e('a1-vocab-travel-kp-ticket',      'ticket')
e('a1-vocab-travel-kp-ticket---s',  'ticket')
e('a1-vocab-travel-kp-aufzug------e','elevator / lift')
e('a1-vocab-travel-kp-bus---se',    'bus')
e('a1-vocab-travel-kp-pass------e', 'passport')
e('a1-vocab-travel-kp-test',        'test')
e('a1-vocab-travel-kp-zug------e',  'train')
e('a1-vocab-travel-kp-abfahrt',     'departure')
e('a1-vocab-travel-kp-ankunft',     'arrival')
e('a1-vocab-travel-kp-autobahn',    'motorway / highway / freeway')
e('a1-vocab-travel-kp-autobahn---en','motorway / highway / freeway')
e('a1-vocab-travel-kp-bahn',        'train / railway')
e('a1-vocab-travel-kp-fahrkarte---n','ticket (public transport)')
e('a1-vocab-travel-kp-rezeption',   'reception / front desk')
e('a1-vocab-travel-kp-stelle',      'position / job / spot')
e('a1-vocab-travel-kp-stra-e---n',  'street / road')
e('a1-vocab-travel-kp-stra-enbahn', 'tram')
e('a1-vocab-travel-kp-fahren',      'to drive / to travel / to ride')
e('a1-vocab-travel-kp-fliegen',     'to fly')
e('a1-vocab-travel-kp-liegen',      'to lie / to be located')
e('a1-vocab-travel-kp-rad',         'cycling / riding a bike', 'Das Kind kann schon Rad fahren.')
e('a1-vocab-travel-kp-rad-fahren',  'to ride a bike / to cycle')
e('a1-vocab-travel-kp-sp-t',        'late')
e('a1-vocab-travel-kp-tun',         'to do')
# ─── A1 vocab-hobbies ────────────────────────────────────────────────────────
e('a1-vocab-hobbies-kp-buch------er-1','book',        'Gute Bücher sind oft sehr teuer.')
e('a1-vocab-hobbies-kp-buch------er-2','dictionary (Wörterbuch)', 'In diesem Wörterbuch finden Sie mehr als 20.000 Wörter.')
e('a1-vocab-hobbies-kp-foto',       'photo / picture')
e('a1-vocab-hobbies-kp-foto---s',   'photo / picture')
e('a1-vocab-hobbies-kp-hobby',      'hobby')
e('a1-vocab-hobbies-kp-hobby---s',  'hobby')
e('a1-vocab-hobbies-kp-kino---s',   'cinema / movie theater')
e('a1-vocab-hobbies-kp-schwimmbad', 'swimming pool')
e('a1-vocab-hobbies-kp-buchstabe',  'letter (of the alphabet)')
e('a1-vocab-hobbies-kp-buchstabe---n','letter (of the alphabet)')
e('a1-vocab-hobbies-kp-film',       'film / movie')
e('a1-vocab-hobbies-kp-film---e',   'film / movie')
e('a1-vocab-hobbies-kp-ort',        'place / town / location')
e('a1-vocab-hobbies-kp-gerade',     'just now / right now')
e('a1-vocab-hobbies-kp-gerade-1',   'just now',     'Da kommt er ja gerade.')
e('a1-vocab-hobbies-kp-gerade-2',   'straight ahead','Gehen Sie immer geradeaus!')
e('a1-vocab-hobbies-kp-geradeaus',  'straight ahead')
e('a1-vocab-hobbies-kp-grad',       'degree(s)',     'Heute haben wir dreißig Grad.')
e('a1-vocab-hobbies-kp-grad--celsius','degree(s) Celsius')
e('a1-vocab-hobbies-kp-lesen',      'to read')
e('a1-vocab-hobbies-kp-spielen',    'to play')
e('a1-vocab-hobbies-kp-spielen-1',  'to play (children)', 'Die Kinder spielen draußen.')
e('a1-vocab-hobbies-kp-wandern',    'to hike / to go hiking')
# ─── A1 vocab-colors ─────────────────────────────────────────────────────────
e('a1-vocab-colors-kp-farbe',       'colour / color')
e('a1-vocab-colors-kp-farbe---n',   'colour / color')
e('a1-vocab-colors-kp-hell',        'bright / light (not dark)')
# ─── A1 vocab-days-months ────────────────────────────────────────────────────
e('a1-vocab-months-kp-datum',       'date')
e('a1-vocab-months-kp-ende',        'end')
e('a1-vocab-months-kp-geburtstag',  'birthday')
e('a1-vocab-months-kp-kunde',       'customer / client (male)')
e('a1-vocab-months-kp-e-mail',      'email')
e('a1-vocab-months-kp-e-mail---s',  'email')
e('a1-vocab-months-kp-mitte',       'middle / centre')
e('a1-vocab-months-kp-stunde---n',  'hour / lesson')
e('a1-vocab-months-kp-gestern',     'yesterday')
e('a1-vocab-months-kp-heute',       'today')
e('a1-vocab-months-kp-mit',         'with / by (transport)')
e('a1-vocab-months-kp-ber',         'over / across / about / via')
# ─── A1 vocab-shopping ───────────────────────────────────────────────────────
e('a1-vocab-shopping-kp-kredit--karte---n','credit card / payment card')
e('a1-vocab-shopping-kp-billig-1',  'cheap / inexpensive',  'Die Jacke kostet nur 10 Euro!')
e('a1-vocab-shopping-kp-angebot',   'offer / special offer / deal')
e('a1-vocab-shopping-kp-gesch-ft---e','shop / store / business')
e('a1-vocab-shopping-kp-laden',     'shop / store')
e('a1-vocab-shopping-kp-gr--e',     'size')
e('a1-vocab-shopping-kp-karte---n-1','postcard / greeting card', 'Ich schreibe meinen Bekannten eine Karte aus dem Urlaub.')
e('a1-vocab-shopping-kp-karte---n-2','playing card',             'Wollen wir Karten spielen?')
e('a1-vocab-shopping-kp-karte---n-3','menu',                     'Bringen Sie mir die Karte, bitte.')
e('a1-vocab-shopping-kp-kasse',     'checkout / cash register / till')
e('a1-vocab-shopping-kp-euer',      'your (plural informal)')
e('a1-vocab-shopping-kp-g-nstig',   'good value / cheap / inexpensive')
e('a1-vocab-shopping-kp-verkaufen', 'to sell')
# ─── A1 vocab-professions ────────────────────────────────────────────────────
e('a1-vocab-professions-kp-arzt------e','doctor / physician')
e('a1-vocab-professions-kp-beamte',    'civil servant / official')
e('a1-vocab-professions-kp-beamte---n','civil servant / official')
e('a1-vocab-professions-kp-beruf---e', 'profession / job / occupation')
e('a1-vocab-professions-kp-chef',      'boss / manager')
e('a1-vocab-professions-kp-fahrer',    'driver')
e('a1-vocab-professions-kp-lehrer',    'teacher')
e('a1-vocab-professions-kp-verk-ufer', 'shop assistant / salesperson')
e('a1-vocab-professions-kp-krank',     'ill / sick')
e('a1-vocab-professions-kp-nie',       'never')
# ─── A2 vocab-health ─────────────────────────────────────────────────────────
e('a2-vocab-health-kp-ab',           'from / starting from / off')
e('a2-vocab-health-kp-als',          'than / as / when (comparison)')
e('a2-vocab-health-kp-an',           'on / at / to (preposition)')
e('a2-vocab-health-kp-auch',         'also / too / as well')
e('a2-vocab-health-kp-aus',          'from / out of')
e('a2-vocab-health-kp-bei',          'near / at / with')
e('a2-vocab-health-kp-auge-2',       'eye',           'Mein rechtes Auge tut seit Sonntag weh.')
e('a2-vocab-health-kp-bein---e',     'leg')
e('a2-vocab-health-kp-ei',           'egg',           'Möchtest du ein Ei zum Frühstück?')
e('a2-vocab-health-kp-fieber--sg',   'fever / temperature')
e('a2-vocab-health-kp-handtuch----er','towel')
e('a2-vocab-health-kp-handy',        'mobile phone / cell phone')
e('a2-vocab-health-kp-handy---s',    'mobile phone / cell phone')
e('a2-vocab-health-kp-handy---s-2',  'mobile number',  'Kannst du mir bitte deine Handynummer geben?')
e('a2-vocab-health-kp-krankenhaus----er',  'hospital')
e('a2-vocab-health-kp-krankenhaus----er-2','hospital (injury)', 'Er hat sich verletzt und muss ins Krankenhaus.')
e('a2-vocab-health-kp-medikament',   'medication / medicine')
e('a2-vocab-health-kp-medikament---e','medication / medicine')
e('a2-vocab-health-kp-ohr---en',     'ear')
e('a2-vocab-health-kp-rezept---e',   'recipe',         'Dieser Kuchen schmeckt super! Kannst du mir bitte das Rezept geben?')
e('a2-vocab-health-kp-rezept---e--2','prescription',   'Dieses Medikament gibt es nur auf Rezept.')
e('a2-vocab-health-kp-bauch----e',   'stomach / tummy / belly')
e('a2-vocab-health-kp-fu--2',        'on foot (zu Fuß)', 'Gehen Sie zu Fuß zur Arbeit?')
e('a2-vocab-health-kp-fu-----e',     'foot')
e('a2-vocab-health-kp-fu-ball----e', 'football / soccer ball')
e('a2-vocab-health-kp-hals----e',    'throat / neck')
e('a2-vocab-health-kp-hals----e-2',  'sore throat',    'Ich habe seit gestern Halsschmerzen.')
e('a2-vocab-health-kp-k-rper',       'body',           'Der Arzt sagt, ich muss etwas für meinen Körper tun.')
e('a2-vocab-health-kp-mund----er',   'mouth')
e('a2-vocab-health-kp-r-cken',       'back (body)')
e('a2-vocab-health-kp-schmerz---en-2','pain / ache',   'Ich habe Bauchschmerzen.')
e('a2-vocab-health-kp-zahn----e',    'tooth')
e('a2-vocab-health-kp-apotheke',     'pharmacy / chemist')
e('a2-vocab-health-kp-apotheke---n', 'pharmacy / chemist')
e('a2-vocab-health-kp-gesundheit',   'health')
e('a2-vocab-health-kp-gesundheit--sg','health')
e('a2-vocab-health-kp-hand----e',    'hand')
e('a2-vocab-health-kp-kranken',      'health insurance (prefix)',  'Bei welcher Krankenkasse sind Sie?')
e('a2-vocab-health-kp-krankenkasse---n','health insurance (company)')
e('a2-vocab-health-kp-krankheit',    'illness / disease')
e('a2-vocab-health-kp-krankheit---en','illness / disease')
e('a2-vocab-health-kp-rezeption',    'reception / front desk')
e('a2-vocab-health-kp-rezeption---en','reception / front desk')
e('a2-vocab-health-kp-tablette',     'tablet / pill',  'Du sollst am Abend zwei Tabletten nehmen.')
e('a2-vocab-health-kp-tablette---n', 'tablet / pill')
e('a2-vocab-health-kp-dr-cken-2',    'to press (a button)', 'Drücken Sie „Bestätigen"!')
e('a2-vocab-health-kp-dr-cken-3',    'to pinch / to be tight (shoes)', 'Meine Schuhe drücken.')
e('a2-vocab-health-kp-dr-cken--dr-ckt','to push / to press')
e('a2-vocab-health-kp-ein',          'a / one (single room)',  'Ein Einzelzimmer ist noch frei.')
e('a2-vocab-health-kp-herzlich',     'warmly / cordially',    'Herzlichen Glückwunsch!')
e('a2-vocab-health-kp-husten--hustet--hat-gehustet','to cough')
e('a2-vocab-health-kp-in',           'in / into')
e('a2-vocab-health-kp-und',          'and')
e('a2-vocab-health-kp-unter',        'under / below / among')
e('a2-vocab-health-kp-verletzen--sich---verletzt',  'to injure (oneself)')
e('a2-vocab-health-kp-verletzen--sich---verletzt-2','to injure (oneself) – past', 'Haben Sie sich verletzt?')
e('a2-vocab-health-kp-warm',         'warm')
e('a2-vocab-health-kp-warm--2',      'warm (cooked meal)',   'Mittags esse ich oft ein warmes Essen.')
e('a2-vocab-health-kp-warm--3',      'warm (clothing)',      'Ich brauche einen warmen Pullover.')
# ─── A2 vocab-weather ────────────────────────────────────────────────────────
e('a2-vocab-weather-kp-aufregend',   'exciting')
e('a2-vocab-weather-kp-aufregend-2', 'exciting (film)',    'Der Film ist nicht besonders aufregend.')
e('a2-vocab-weather-kp-bew-lkt',     'cloudy / overcast')
e('a2-vocab-weather-kp-eis--sg',     'ice cream / ice')
e('a2-vocab-weather-kp-fleisch',     'meat',              'Fleisch mag ich nicht.')
e('a2-vocab-weather-kp-fleisch--sg', 'meat')
e('a2-vocab-weather-kp-gleis',       'platform / track (train)')
e('a2-vocab-weather-kp-gleis---e',   'platform / track (train)')
e('a2-vocab-weather-kp-reiseb-ro',   'travel agency')
e('a2-vocab-weather-kp-reiseb-ro---s',  'travel agency')
e('a2-vocab-weather-kp-reiseb-ro---s-2','travel agency',  'Wir buchen die Reise im Reisebüro.')
e('a2-vocab-weather-kp-wetter',      'weather',           'Heute ist das Wetter gut: Es ist sonnig und warm.')
e('a2-vocab-weather-kp-wetter--sg',  'weather')
e('a2-vocab-weather-kp-wetter--sg----2','weather (bad)',  'Wir hatten im Urlaub schlechtes Wetter.')
e('a2-vocab-weather-kp-l',           'oil',               'Machen wir den Salat mit Öl?')
e('a2-vocab-weather-kp-ausweis---e', 'ID card / identity card')
e('a2-vocab-weather-kp-bleistift---e','pencil')
e('a2-vocab-weather-kp-k-hl',        'fridge (prefix)',   'Haben wir noch Milch? – Ja, im Kühlschrank.')
e('a2-vocab-weather-kp-k-hlschrank----e','refrigerator / fridge')
e('a2-vocab-weather-kp-preis',       'price',             'Die Preise sind hier viel höher als bei uns.')
e('a2-vocab-weather-kp-preis---e',   'price')
e('a2-vocab-weather-kp-regen--sg',   'rain')
e('a2-vocab-weather-kp-reis--sg',    'rice',              'Ich esse gern Reis mit Gemüse und Fisch.')
e('a2-vocab-weather-kp-reisef-hrer-----2','tour guide (person)', 'Unser Reiseführer heißt Robert und ist sehr sympathisch.')
e('a2-vocab-weather-kp-schnee--sg',  'snow')
e('a2-vocab-weather-kp-reise',       'trip / journey / travel')
e('a2-vocab-weather-kp-reise---n',   'trip / journey / travel')
e('a2-vocab-weather-kp-reise---n-2', 'business trip',     'Ich mache nächste Woche eine Geschäftsreise.')
e('a2-vocab-weather-kp-speisekarte---n','menu')
e('a2-vocab-weather-kp-wolke---n',   'cloud')
e('a2-vocab-weather-kp-hei--2',      'hot',               'Mir ist heiß. Kannst du das Fenster öffnen?')
e('a2-vocab-weather-kp-hei-en--hei-t--hat-gehei-en',   'to be called (name)', 'Ich heiße Charlotte Meier.')
e('a2-vocab-weather-kp-hei-en--hei-t--hat-gehei-en-2', 'to be called (word)',  'Wie heißt das auf Deutsch?')
e('a2-vocab-weather-kp-kalt-2',      'cold',              'Der Kaffee ist kalt. Ich möchte ihn nicht mehr trinken.')
e('a2-vocab-weather-kp-leise',       'quiet / softly')
e('a2-vocab-weather-kp-meist',       'most (prefix)')
e('a2-vocab-weather-kp-meistens',    'usually / most of the time')
e('a2-vocab-weather-kp-preiswert',   'good value / worth the price')
e('a2-vocab-weather-kp-reisen--reist-2','to travel (past)', 'Wir sind schon nach Spanien gereist.')
e('a2-vocab-weather-kp-so',          'so / like that / in this way')
e('a2-vocab-weather-kp-sonnig',      'sunny')
e('a2-vocab-weather-kp-trocken',     'dry')
e('a2-vocab-weather-kp-verreisen--verreist',  'to go on a trip / to travel away')
e('a2-vocab-weather-kp-verreisen--verreist-2','to go on a trip (away)', 'Frau Doktor Müller ist zur Zeit verreist.')
e('a2-vocab-weather-kp-vor',         'before / ago')
e('a2-vocab-weather-kp-vorher',      'before / beforehand')
e('a2-vocab-weather-kp-windig',      'windy')
e('a2-vocab-weather-kp-wo',          'where')
e('a2-vocab-weather-kp-zum-beispiel','for example / e.g.')
e('a2-vocab-weather-kp-berweisen---berweist',  'to transfer (money)')
e('a2-vocab-weather-kp-berweisen---berweist--2','to transfer (money)', 'Ich überweise dir das Geld.')
# ─── A2 vocab-work ───────────────────────────────────────────────────────────
e('a2-vocab-work-kp-arbeiten-2',     'to work (profession)', 'Ich arbeite als Krankenschwester in einem Krankenhaus.')
e('a2-vocab-work-kp-arbeitslos',     'unemployed')
e('a2-vocab-work-kp-arbeitslos-2',   'unemployed (long-term)', 'Es gibt bei uns viele Leute, die schon lange arbeitslos sind.')
e('a2-vocab-work-kp-auf',            'on / onto')
e('a2-vocab-work-kp-bestellen',      'to order')
e('a2-vocab-work-kp-bestellen-2',    'to order (a book for someone)', 'Dieses Buch haben wir nicht da. Sollen wir es für Sie bestellen?')
e('a2-vocab-work-kp-b-ro-2',         'office (closed)',   'Unser Büro ist bis Dienstag geschlossen.')
e('a2-vocab-work-kp-b-ro---s',       'office')
e('a2-vocab-work-kp-gehalt----er',   'salary / wage')
e('a2-vocab-work-kp-gesch-ft',       'shop / business')
e('a2-vocab-work-kp-leben',          'life',              'Hier in London ist das Leben teuer.')
e('a2-vocab-work-kp-praktikum---a',  'internship / work placement')
e('a2-vocab-work-kp-projekt---e',    'project')
e('a2-vocab-work-kp-beruf',          'profession / job')
e('a2-vocab-work-kp-beruf---e',      'profession / job')
e('a2-vocab-work-kp-chef---s---die-chefin---ne', 'boss / manager')
e('a2-vocab-work-kp-kollege---n---die-kollegin---n', 'colleague')
e('a2-vocab-work-kp-mitarbeiter',    'employee / staff member', 'Unsere Firma hat sieben Mitarbeiter.')
e('a2-vocab-work-kp-termin---e',     'appointment')
e('a2-vocab-work-kp-termin---e--2',  'appointment (dentist)', 'Ich habe heute einen Termin bei meiner Zahnärztin.')
e('a2-vocab-work-kp-urlaub',         'holiday / vacation')
e('a2-vocab-work-kp-urlaub---e',     'holiday / vacation')
e('a2-vocab-work-kp-vertrag----e',   'contract')
e('a2-vocab-work-kp-arbeit',         'work / job')
e('a2-vocab-work-kp-arbeit---en',    'work / job')
e('a2-vocab-work-kp-baustelle',      'construction site')
e('a2-vocab-work-kp-baustelle---n',  'construction site')
e('a2-vocab-work-kp-chefin',         'female boss / manager')
e('a2-vocab-work-kp-erfahrung',      'experience')
e('a2-vocab-work-kp-erfahrung---en', 'experience')
e('a2-vocab-work-kp-firma---en',     'company / firm')
e('a2-vocab-work-kp-haltestelle',    'bus/tram stop')
e('a2-vocab-work-kp-haltestelle---n','bus/tram stop')
e('a2-vocab-work-kp-stelle---n',     'position / job',      'Ich habe eine neue Stelle. Ich arbeite jetzt bei Mercedes.')
e('a2-vocab-work-kp-stelle---n-2',   'place / spot',        'Wir treffen uns hier an dieser Stelle.')
e('a2-vocab-work-kp-zeit',           'time')
e('a2-vocab-work-kp-erst',           'only / not until / first')
e('a2-vocab-work-kp-halten--h-lt--hat-gehalten',   'to stop (transport)')
e('a2-vocab-work-kp-halten--h-lt--hat-gehalten-2', 'to hold',             'Kannst du mal kurz meine Jacke halten?')
e('a2-vocab-work-kp-herstellen--stellt-her--hat-he','to produce / to manufacture')
e('a2-vocab-work-kp-stellen--stellt','to place / to put')
e('a2-vocab-work-kp-voll',           'full')
e('a2-vocab-work-kp-vorstellen--sich---vorgestellt','to introduce oneself')
e('a2-vocab-work-kp-ber',            'over / about / via')
# ─── A2 vocab-education ──────────────────────────────────────────────────────
e('a2-vocab-education-kp-bild',      'picture / image',     'Hast du ein Bild von deinem Sohn?')
e('a2-vocab-education-kp-fach----er','subject (school)')
e('a2-vocab-education-kp-studium--sg','studies / degree')
e('a2-vocab-education-kp-thema',     'topic / subject / theme')
e('a2-vocab-education-kp-zeugnis---se','school report / certificate')
e('a2-vocab-education-kp-kurs---e',  'course / class')
e('a2-vocab-education-kp-sch-ler------die-sch-lerin---n','pupil / student')
e('a2-vocab-education-kp-unterricht','lessons / class / instruction', 'Der Unterricht dauert bis 19 Uhr.')
e('a2-vocab-education-kp-unterricht--sg','lessons / instruction')
e('a2-vocab-education-kp-ausbildung','training / apprenticeship')
e('a2-vocab-education-kp-ausbildung--en','training / apprenticeship')
e('a2-vocab-education-kp-bibliothek','library')
e('a2-vocab-education-kp-bibliothek---en','library')
e('a2-vocab-education-kp-note---n',  'grade / mark')
e('a2-vocab-education-kp-pr-fung---en','exam / test')
e('a2-vocab-education-kp-schule---n','school')
e('a2-vocab-education-kp-schule---n-2','school (location)',  'Die Schule ist gleich hier um die Ecke.')
e('a2-vocab-education-kp-universit-t---en','university')
e('a2-vocab-education-kp-einfach',   'simple / easy')
e('a2-vocab-education-kp-einfach-2', 'simpler / more simply',  'Kannst du es bitte einfacher sagen?')
e('a2-vocab-education-kp-einfach-3', 'one-way (ticket)',       'Hin und zurück? – Nein, bitte nur eine einfache Fahrt nach Berlin.')
e('a2-vocab-education-kp-eng',       'tight / narrow',         'Diese Hose ist zu eng. Gibt es sie auch eine Nummer größer?')
e('a2-vocab-education-kp-kennenlernen--lernt-kennen--ha','to get to know / to meet')
e('a2-vocab-education-kp-lernen--lernt--hat-gelernt','to learn / to study')
e('a2-vocab-education-kp-rund',      'round')
# ─── A2 vocab-services ───────────────────────────────────────────────────────
e('a2-vocab-services-kp-formular',   'form')
e('a2-vocab-services-kp-formular---e','form')
e('a2-vocab-services-kp-konto',      'bank account',      'Das Geld überweisen wir am ersten März auf Ihr Konto.')
e('a2-vocab-services-kp-konto---en', 'bank account')
e('a2-vocab-services-kp-paket',      'package / parcel')
e('a2-vocab-services-kp-paket---e',  'package / parcel')
e('a2-vocab-services-kp-poster',     'poster',            'Das Poster hängt über dem Bett.')
e('a2-vocab-services-kp-rathaus----er',  'town hall / city hall')
e('a2-vocab-services-kp-rathaus----er-2','town hall (registration)', 'Sie müssen sich im Rathaus anmelden.')
e('a2-vocab-services-kp-brief---e',  'letter')
e('a2-vocab-services-kp-f-hrerschein-2', 'driving licence (exam)',  'Sie hat die Führerscheinprüfung bestanden.')
e('a2-vocab-services-kp-f-hrerschein---e','driving licence')
e('a2-vocab-services-kp-anmeldung',  'registration')
e('a2-vocab-services-kp-anmeldung--en','registration')
e('a2-vocab-services-kp-bank-2',     'bench',             'Kommt, wir setzen uns auf diese Bank.')
e('a2-vocab-services-kp-bank---en',  'bank')
e('a2-vocab-services-kp-briefmarke---n','stamp (postage)')
e('a2-vocab-services-kp-polizei--sg','police')
e('a2-vocab-services-kp-post--sg',   'post office')
e('a2-vocab-services-kp-post--sg----2','mail / post',     'Ist Post für mich da?')
e('a2-vocab-services-kp-postkarte---n','postcard')
e('a2-vocab-services-kp-postleitzahl---en','postal code')
e('a2-vocab-services-kp-werkstatt----en','workshop / repair shop / garage')
e('a2-vocab-services-kp-zahl',       'number / figure')
e('a2-vocab-services-kp-sicher',     'safe / certain / sure')
# A2-services KPs that need cleanup of combined garbage
e('a2-vocab-services-kp-postkarte',  'postcard',          'Schreibst du mir eine Postkarte aus Kanada?')
# ─── A2 vocab-entertainment ──────────────────────────────────────────────────
e('a2-vocab-entertainment-kp-buchen','to book / to reserve')
e('a2-vocab-entertainment-kp-buchstabieren','to spell out')
e('a2-vocab-entertainment-kp-buch-2','dictionary / reference book', 'In diesem Wörterbuch finden Sie mehr als 20.000 Wörter.')
e('a2-vocab-entertainment-kp-buch----er','book')
e('a2-vocab-entertainment-kp-festival',   'festival')
e('a2-vocab-entertainment-kp-festival---s','festival')
e('a2-vocab-entertainment-kp-internet--sg',   'internet')
e('a2-vocab-entertainment-kp-internet--sg---2','internet (browsing)', 'Du kannst im Internet Musik hören oder Spiele spielen.')
e('a2-vocab-entertainment-kp-kino---s',   'cinema / movie theater')
e('a2-vocab-entertainment-kp-konzert---e','concert')
e('a2-vocab-entertainment-kp-lied',       'song')
e('a2-vocab-entertainment-kp-lied---er',  'song')
e('a2-vocab-entertainment-kp-mobiltelefon---e','mobile phone / cell phone')
e('a2-vocab-entertainment-kp-programm---e',  'programme / schedule')
e('a2-vocab-entertainment-kp-programm---e-2','programme (cinema/events)', 'Was kommt heute im Kino? Hast du das Programm hier?')
e('a2-vocab-entertainment-kp-radio',      'radio')
e('a2-vocab-entertainment-kp-radio---s',  'radio')
e('a2-vocab-entertainment-kp-spiel---e',  'game / match')
e('a2-vocab-entertainment-kp-telefon',    'telephone')
e('a2-vocab-entertainment-kp-telefon---e','telephone')
e('a2-vocab-entertainment-kp-theater',    'theatre')
e('a2-vocab-entertainment-kp-ticket',     'ticket')
e('a2-vocab-entertainment-kp-ticket---s', 'ticket')
e('a2-vocab-entertainment-kp-apparat---e','device / appliance',  'Was machen wir mit deinem alten Apparat?')
e('a2-vocab-entertainment-kp-apparat-2',  'camera (Fotoapparat)', 'Ich habe einen neuen Fotoapparat.')
e('a2-vocab-entertainment-kp-buchstabe---n','letter (alphabet)')
e('a2-vocab-entertainment-kp-computer',   'computer')
e('a2-vocab-entertainment-kp-eintritt',   'admission / entry fee')
e('a2-vocab-entertainment-kp-film---e',   'film / movie')
e('a2-vocab-entertainment-kp-fotoapparat',    'camera',  'Ich möchte mir einen Fotoapparat kaufen.')
e('a2-vocab-entertainment-kp-fotoapparat---e','camera')
e('a2-vocab-entertainment-kp-band---s',   'band',   'Was ist deine Lieblingsband? Anton spielt in einer Band.')
e('a2-vocab-entertainment-kp-musik--sg',  'music')
e('a2-vocab-entertainment-kp-musik--sg---2','music (preference)', 'Spanische Musik gefällt mir gut.')
e('a2-vocab-entertainment-kp-nachricht---en',  'news (TV)',   'Ich sehe abends immer die Nachrichten im Fernsehen.')
e('a2-vocab-entertainment-kp-nachricht---en-3','message',     'Ich schreibe dir später eine Nachricht.')
e('a2-vocab-entertainment-kp-nachricht---en-4','messages (inbox)', 'Sie haben keine neuen Nachrichten.')
e('a2-vocab-entertainment-kp-sendung---en',  'TV programme / broadcast')
e('a2-vocab-entertainment-kp-sendung---en-2','broadcast (age restriction)', 'Diese Sendung ist nicht für Jugendliche unter 18 Jahren.')
e('a2-vocab-entertainment-kp-veranstaltung---en','event')
e('a2-vocab-entertainment-kp-zeitschrift---en','magazine')
e('a2-vocab-entertainment-kp-zeitung---en',   'newspaper')
e('a2-vocab-entertainment-kp-zeitung---en--2','newspaper (today\'s)',  'Wo ist die Zeitung von heute?')
e('a2-vocab-entertainment-kp-fernsehen--sieht-fern','to watch television')
e('a2-vocab-entertainment-kp-klappen--klappt--hat-geklappt',  'to work out / to be okay')
e('a2-vocab-entertainment-kp-klappen--klappt--hat-geklappt-', 'to work out (past)', 'Wie war die Reise? - Gut, es hat alles super geklappt.')
e('a2-vocab-entertainment-kp-nach',            'to / after / according to')
e('a2-vocab-entertainment-kp-online',          'online')
e('a2-vocab-entertainment-kp-online-2',        'online (connectivity)',   'Ich bin erst heute Abend wieder online.')
e('a2-vocab-entertainment-kp-online-3',        'online (transfer)',       'Sie können das Geld auch online überweisen.')
e('a2-vocab-entertainment-kp-spielen--spielt', 'to play')
e('a2-vocab-entertainment-kp-spielen--spielt-3','to play (instrument)',   'Jakob spielt Klavier.')
e('a2-vocab-entertainment-kp-telefonieren--hat-telefoniert','to phone / to call')
e('a2-vocab-entertainment-kp-telefonieren--telefoniert',    'to phone / to call')
# Entertainment KPs with junk appended
e('a2-vocab-entertainment-kp-apparat',    'device / appliance',  'Was machen wir mit deinem alten Apparat?')
e('a2-vocab-entertainment-kp-band',       'band',                'Was ist deine Lieblingsband? Anton spielt in einer Band.')
# ─── A2 vocab-clothing ───────────────────────────────────────────────────────
e('a2-vocab-clothing-kp-aufpassen',   'to watch out / to be careful')
e('a2-vocab-clothing-kp-aufpassen-2', 'to look after / to watch over',  'Der Babysitter passt heute Abend auf die Kinder auf.')
e('a2-vocab-clothing-kp-bringen',     'to bring')
e('a2-vocab-clothing-kp-bier',        'beer',              'Noch ein Bier, bitte.')
e('a2-vocab-clothing-kp-hemd---en',   'shirt')
e('a2-vocab-clothing-kp-kleid---er',  'dress')
e('a2-vocab-clothing-kp-t-shirt---s', 'T-shirt',           'Haben Sie dieses T-Shirt auch in M?')
e('a2-vocab-clothing-kp-taschengeld--sg','pocket money / allowance')
e('a2-vocab-clothing-kp-anzug----e',  'suit')
e('a2-vocab-clothing-kp-mantel',      'coat')
e('a2-vocab-clothing-kp-pullover',    'jumper / sweater / pullover')
e('a2-vocab-clothing-kp-ring',        'ring')
e('a2-vocab-clothing-kp-ring---e',    'ring')
e('a2-vocab-clothing-kp-schalter',    'counter / service window')
e('a2-vocab-clothing-kp-schalter-----2','light switch',   'Der Lichtschalter ist neben der Tür.')
e('a2-vocab-clothing-kp-schuh---e-2', 'shoe (tight)',     'Die neuen Schuhe sind mir zu eng. Sie drücken.')
e('a2-vocab-clothing-kp-stiefel',     'boot')
e('a2-vocab-clothing-kp-bluse---n',   'blouse')
e('a2-vocab-clothing-kp-brille-2',    'glasses',          'Mit dieser Brille kann ich nicht mehr gut sehen.')
e('a2-vocab-clothing-kp-gr--e',       'size')
e('a2-vocab-clothing-kp-gr--e---n',   'size')
e('a2-vocab-clothing-kp-hose---n',    'trousers / pants')
e('a2-vocab-clothing-kp-jacke---n',   'jacket / coat')
e('a2-vocab-clothing-kp-kleidung--sg','clothing / clothes')
e('a2-vocab-clothing-kp-mode',        'fashion')
e('a2-vocab-clothing-kp-mode---n',    'fashion')
e('a2-vocab-clothing-kp-m-tze---n',   'hat / beanie / cap')
e('a2-vocab-clothing-kp-tasche---n',  'bag / handbag',    'Ich habe die Schlüssel in der Tasche.')
e('a2-vocab-clothing-kp-tasche---n-2','bag (travel)',     'Ich habe nicht viel Gepäck. Nur eine Tasche.')
e('a2-vocab-clothing-kp-uhr---en--2', 'watch / clock',   'Geht deine Uhr richtig?')
e('a2-vocab-clothing-kp-dringend',    'urgent / urgently')
e('a2-vocab-clothing-kp-ja',          'yes')
e('a2-vocab-clothing-kp-man',         'one / you (impersonal)')
e('a2-vocab-clothing-kp-mit----mitbringen--kommen--mac','with (and in compound verbs: mitbringen, mitkommen...)')
e('a2-vocab-clothing-kp-modern',      'modern / fashionable')
e('a2-vocab-clothing-kp-passen--passt--hat-gepasst',  'to fit / to suit')
e('a2-vocab-clothing-kp-passen--passt--hat-gepasst-2','to fit / to match', 'Welches Wort passt? Wählen Sie.')
e('a2-vocab-clothing-kp-pro',         'per / each')
e('a2-vocab-clothing-kp-sich-umziehen--zieht-sich-um', 'to get changed / to change clothes')
e('a2-vocab-clothing-kp-sich-umziehen--zieht-sich-um--','to get changed (past)', 'Er hat sich schnell umgezogen.')
e('a2-vocab-clothing-kp-tief',        'deep')
e('a2-vocab-clothing-kp-um',          'at (time) / around')
e('a2-vocab-clothing-kp-umziehen--zieht-um',  'to move (house)')
e('a2-vocab-clothing-kp-umziehen--zieht-um--2','to move house (past)', 'Er ist in eine neue Wohnung umgezogen.')
e('a2-vocab-clothing-kp-verpassen--verpasst',  'to miss (bus/train)')
e('a2-vocab-clothing-kp-zu',          'to / closed / too (adverb)')
# Clothing KPs with junk appended
e('a2-vocab-clothing-kp-taschengeld','pocket money / allowance', 'Wie viel Taschengeld bekommen deine Kinder?')
# ─── A2 vocab-emotions ───────────────────────────────────────────────────────
e('a2-vocab-emotions-kp-beliebt',     'popular / well-liked')
e('a2-vocab-emotions-kp-b-se',        'angry / upset')
e('a2-vocab-emotions-kp-b-se-2',      'upset / cross with',  'Hoffentlich bist du mir nicht böse.')
e('a2-vocab-emotions-kp-angst-2',     'fear / anxiety (of something)')
e('a2-vocab-emotions-kp-freundlich-2','friendly / kind (letters: Mit freundlichen Grüßen = Yours sincerely)')
e('a2-vocab-emotions-kp-f-hlen--sich--2','to feel (unwell)',  'Ich fühle mich heute nicht gut.')
e('a2-vocab-emotions-kp-f-hlen--sich---f-hlt','to feel')
e('a2-vocab-emotions-kp-gern--lieber--am-liebsten',  'gladly / with pleasure')
e('a2-vocab-emotions-kp-gern--lieber--am-liebsten-2','prefer / rather',  'Ich trinke lieber einen Tee.')
e('a2-vocab-emotions-kp-gern--lieber--am-liebsten-3','most of all',      'Am liebsten trinke ich Kaffee.')
e('a2-vocab-emotions-kp-gl-cklich-2', 'happy / lucky',  'Ein glückliches neues Jahr!')
e('a2-vocab-emotions-kp-lachen--lacht--hat-gelacht','to laugh')
e('a2-vocab-emotions-kp-lang',        'long')
e('a2-vocab-emotions-kp-langweilig-2','boring',        'Sie findet Fußball sehr langweilig.')
e('a2-vocab-emotions-kp-lieb--2',     'rather / prefer',  'Ich fahre lieber mit dem Zug als mit dem Bus.')
e('a2-vocab-emotions-kp-lieb--3',     'would rather',     'Möchtest du Pommes oder lieber eine Pizza?')
e('a2-vocab-emotions-kp-lieblings',   'favourite (prefix: Lieblingsfarbe = favourite colour)')
e('a2-vocab-emotions-kp-lustig',      'funny / amusing')
e('a2-vocab-emotions-kp-lustig-2',    'funny (films)',  'Ich mag lustige Filme.')
e('a2-vocab-emotions-kp-m-gen--mag--hat-gemocht','to like')
e('a2-vocab-emotions-kp-m-de',        'tired')
e('a2-vocab-emotions-kp-nett',        'nice / friendly')
e('a2-vocab-emotions-kp-nett-2',      'kind / nice of you',  'Das ist sehr nett von dir.')
e('a2-vocab-emotions-kp-verlieben--sich---verliebt',  'to fall in love')
e('a2-vocab-emotions-kp-verlieben--sich---verliebt-2','to fall in love (with someone)', 'Er hat sich in sie verliebt.')
e('a2-vocab-emotions-kp-weil',        'because')
e('a2-vocab-emotions-kp-weinen--weint','to cry / to weep')
e('a2-vocab-emotions-kp-zufrieden',   'satisfied / content')
e('a2-vocab-emotions-kp-rgern--sich', 'to get annoyed / to be upset')
# ─── A2 vocab-culture ────────────────────────────────────────────────────────
e('a2-vocab-culture-kp-brauchen',    'to need')
e('a2-vocab-culture-kp-brauchen-2',  'to need any more / to still need',  'Brauchst du die Zeitung noch oder kann ich sie haben?')
e('a2-vocab-culture-kp-fest-2',      'party / celebration',  'Am Wochenende feiern wir ein Fest. Meine Tochter hat Geburtstag.')
e('a2-vocab-culture-kp-feier',       'party / celebration (die Feier)',  'Wann hast du Feierabend?')
e('a2-vocab-culture-kp-feier-2',     'public holiday',  'Am ersten Mai ist ein Feiertag.')
e('a2-vocab-culture-kp-feier---n',   'party / celebration',  'Wann hast du Feierabend?')
e('a2-vocab-culture-kp-kirche---n',  'church')
e('a2-vocab-culture-kp-kultur',      'culture',          'Ich finde fremde Länder und Kulturen sehr interessant.')
e('a2-vocab-culture-kp-kultur---en', 'culture')
e('a2-vocab-culture-kp-kultur---en-2','culture / arts scene',  'Jana interessiert sich sehr für Kultur. Sie geht jede Woche ins Theater oder ins Museum.')
e('a2-vocab-culture-kp-feiern-2',    'to celebrate',    'Die Feier war sehr schön.')
e('a2-vocab-culture-kp-feiern--feiert','to celebrate')
e('a2-vocab-culture-kp-neu',         'new')
# ─── A2 vocab-directions ─────────────────────────────────────────────────────
e('a2-vocab-directions-kp-daneben',  'next to it / beside it')
e('a2-vocab-directions-kp-stadtplan----e','city map / street map')
e('a2-vocab-directions-kp-weg',      'way / path / route')
e('a2-vocab-directions-kp-ampel-2',  'traffic light (instruction)', 'Nach der Ampel musst du nach links fahren.')
e('a2-vocab-directions-kp-ampel---n','traffic lights')
e('a2-vocab-directions-kp-ecke---n', 'corner')
e('a2-vocab-directions-kp-ecke---n-2','corner (room)',   'Wir stellen das Regal in die Ecke.')
e('a2-vocab-directions-kp-kreuzung---en','crossroads / intersection')
e('a2-vocab-directions-kp-drau-en',  'outside / outdoors')
e('a2-vocab-directions-kp-drau-en-2','outside (no dogs)',  'Hunde müssen draußen bleiben.')
e('a2-vocab-directions-kp-drinnen',  'inside / indoors')
e('a2-vocab-directions-kp-drinnen-2','inside (here)',   'Hier drinnen ist es sehr warm.')
e('a2-vocab-directions-kp-echt',     'real / genuine')
e('a2-vocab-directions-kp-gegen',    'against / towards')
e('a2-vocab-directions-kp-gegen-ber-2','opposite / across the street')
e('a2-vocab-directions-kp-gerade',   'just now / at the moment')
e('a2-vocab-directions-kp-hinten',   'at the back / behind')
e('a2-vocab-directions-kp-hinten-2', 'exit at the back',  'Bitte hinten aussteigen!')
e('a2-vocab-directions-kp-kosten--kostet--hat-gekostet','to cost')
e('a2-vocab-directions-kp-kostenlos','free of charge / free')
e('a2-vocab-directions-kp-nebenan',  'next door')
e('a2-vocab-directions-kp-oben',     'above / upstairs')
e('a2-vocab-directions-kp-recht',    'right (recht haben = to be right)',  'Du hast (nicht) recht.')
e('a2-vocab-directions-kp-schmecken--schmeckt',  'to taste good / to like the taste')
e('a2-vocab-directions-kp-schmecken--schmeckt-2','to taste (past)',  'Hat es Ihnen geschmeckt?')
e('a2-vocab-directions-kp-unten',    'below / downstairs')
e('a2-vocab-directions-kp-wecken--weckt',  'to wake (someone) up')
e('a2-vocab-directions-kp-wecken--weckt--2','to be woken up (passive)', 'Ich bin um sechs Uhr geweckt worden.')

# ─── Entries missed on first pass ────────────────────────────────────────────
# A1 family
e('a1-vocab-family-kp-frau',        'woman / wife')
e('a1-vocab-family-kp-frau---en-1', 'woman',         'Das ist Frau Becker.')
e('a1-vocab-family-kp-nicht',       'not')
# A1 food (misc words)
e('a1-vocab-food-kp-allein',        'alone / by oneself')
e('a1-vocab-food-kp-aus-sein-1',    'to be off / switched off',  'Das Licht ist aus.')
e('a1-vocab-food-kp-aus-sein-2',    'to be finished / over (school, etc.)', 'Die Schule ist aus.')
e('a1-vocab-food-kp-dein',          'your (singular informal)')
e('a1-vocab-food-kp-dein--1',       'your (singular informal)',  'Ist das dein Auto?')
e('a1-vocab-food-kp-dein--2',       'yours (pronoun)',           'Ist das deins?')
e('a1-vocab-food-kp-karte',         'card / postcard / map / menu')
e('a1-vocab-food-kp-gleich',        'same / right away / makes no difference')
e('a1-vocab-food-kp-gleich-1',      "doesn't matter / all the same", 'Das ist mir gleich.')
e('a1-vocab-food-kp-gleich-3',      'right away / in a moment',  'Ich komme gleich.')
e('a1-vocab-food-kp-reisen',        'to travel')
e('a1-vocab-food-kp-scheinen',      'to shine / to seem')
# A1 travel
e('a1-vocab-travel-kp-koffer',      'suitcase')
# A1 hobbies – fix "Wörterbuch" umlaut in english translation
e('a1-vocab-hobbies-kp-buch------er-2','dictionary / reference book',
  'In diesem Wörterbuch finden Sie mehr als 20.000 Wörter.')
# A1 months (Goethe pairing entries: german=Apr, english=Oct etc.)
e('a1-vocab-months-kp-april',       'April',    'Im April ist oft schlechtes Wetter.')
e('a1-vocab-months-kp-februar',     'February', 'Der Februar ist der kürzeste Monat.')
e('a1-vocab-months-kp-mai',         'May',      'Im Mai blühen viele Blumen.')
e('a1-vocab-months-kp-vormittag',   'morning / before noon')
e('a1-vocab-months-kp-wochentag',   'weekday')
e('a1-vocab-months-kp-minute',      'minute')
e('a1-vocab-months-kp-sekunde',     'second')
e('a1-vocab-months-kp-stunde',      'hour / lesson')
# A1 shopping
e('a1-vocab-shopping-kp-billig-2',  'cheap (exclamation)',  'Die ist aber billig!')
# A1 professions
e('a1-vocab-professions-kp-student',    'student (male)')
e('a1-vocab-professions-kp-student---en','student (male)')
# A2 health
e('a2-vocab-health-kp-auge---n',    'eye')
e('a2-vocab-health-kp-fu--2',       'on foot',   'Gehen Sie zu Fuß zur Arbeit?')  # no umlaut in value
e('a2-vocab-health-kp-schmerz',     'pain / ache')
e('a2-vocab-health-kp-schmerz---en','pain / ache')
# A2 weather
e('a2-vocab-weather-kp-reis',       'rice',      'Ich esse gern Reis mit Gemüse und Fisch.')
e('a2-vocab-weather-kp-wind---e',   'wind')
e('a2-vocab-weather-kp-sonne---n',  'sun')
e('a2-vocab-weather-kp-reisen--reist','to travel')
# A2 work
e('a2-vocab-work-kp-bestellen-3',   'to order (past form: hat bestellt)',  'Sie hat das Buch bestellt.')
e('a2-vocab-work-kp-praktikum',     'internship / work placement', 'Ich mache ein Praktikum bei Siemens.')
e('a2-vocab-work-kp-stelle',        'position / job / spot')
# A2 education
e('a2-vocab-education-kp-student---en---die-studentin--','student',
  'Ich bin Studentin.')
# A2 services
e('a2-vocab-services-kp-karte',     'card / map / menu / ticket')
# A2 entertainment – verb past-participle-only KPs → treat as verb entries
e('a2-vocab-entertainment-kp-buchen-3',       'to book (past: hat gebucht)',       'Sie hat den Flug online gebucht.')
e('a2-vocab-entertainment-kp-buchstabieren-3','to spell out (past: hat buchstabiert)', 'Er hat seinen Namen buchstabiert.')
e('a2-vocab-entertainment-kp-buch',           'book',   'Das Buch ist fantastisch. Du musst es unbedingt lesen!')
e('a2-vocab-entertainment-kp-fernsehen-2',    'to watch TV (past: hat ferngesehen)', 'Er hat den ganzen Abend ferngesehen.')
# A2 clothing – verb past-participle-only KPs
e('a2-vocab-clothing-kp-aufpassen-3',  'to watch out (past: hat aufgepasst)', 'Er hat gut aufgepasst.')
e('a2-vocab-clothing-kp-bringen-2',    'to bring (past: hat gebracht)',       'Sie hat Blumen mitgebracht.')
e('a2-vocab-clothing-kp-rock----e',    'skirt')
# A2 emotions – fix umlaut in my own translation
e('a2-vocab-emotions-kp-freundlich-2','friendly / kind (formal letter: "Mit freundlichen Grussen" = Yours sincerely)',
  'Mit freundlichen Grüßen')
e('a2-vocab-emotions-kp-lieben--liebt--hat-geliebt','to love')
# A2 culture
e('a2-vocab-culture-kp-brauchen-3',   'to need (past: hat gebraucht)', 'Er hat keinen Arzt gebraucht.')
# A2 education misc
e('a2-vocab-education-kp-kenne',      'to know (ich kenne = I know)',
  'Die meisten Nachbarn kenne ich noch nicht.')

# ─── helpers ─────────────────────────────────────────────────────────────────
def has_german(text):
    """True if text contains German-specific characters or starts like a German sentence."""
    if text.startswith('TODO:'):  # our own marker from a previous run
        return True
    if any(c in text for c in 'äöüßÄÖÜ'):
        return True
    lo = text.lower()
    starters = ('ich ', 'du ', 'er ', 'sie ', 'wir ', 'ihr ', 'der ', 'die ', 'das ',
                 'ein ', 'eine ', 'einen ', 'dem ', 'den ', 'des ', 'ist ', 'sind ',
                 'hat ', 'haben ', 'gehen ', 'kommen ', 'hin ', 'auf ', 'ab ',
                 'bitte ', 'danke ', 'guten ', 'herzlich', 'vielen ')
    return any(lo.startswith(s) for s in starters)

def clean_example(raw):
    """Return a clean German example sentence from the old english field."""
    # Strip leading Goethe list annotations like "(Sg.) ", "(pl.) "
    s = re.sub(r'^\([^)]+\)\s*', '', raw).strip()
    # Take only up to the first complete sentence (stop before appended junk)
    # Junk patterns: " der Automat," / " empfehlen, " / " tot " etc.
    # Strategy: take text up to and including the first sentence-ending punctuation
    m = re.search(r'^(.+?[.!?])\s', s)
    if m:
        candidate = m.group(1).strip()
        # Only use it if it looks like a real sentence (>= 5 words)
        if len(candidate.split()) >= 3:
            return candidate
    return s.split('\n')[0].strip()

def process_topics(topics):
    kept = []
    changed = 0
    removed = 0
    for t in topics:
        before = len(t.get('knowledge_points', []))
        t['knowledge_points'] = [kp for kp in t.get('knowledge_points', [])
                                  if kp['id'] not in REMOVE_IDS]
        removed += before - len(t['knowledge_points'])
        for kp in t['knowledge_points']:
            pd = kp.get('prompt_data', {})
            if pd.get('type') != 'vocabulary':
                continue
            kid = kp['id']
            en  = pd.get('english', '')
            # Skip KPs already fixed or not needing a fix
            if not has_german(en):
                continue
            if kid in EN:
                new_en, new_ex = EN[kid]
                pd['english'] = new_en
                if new_ex is not None:
                    pd['example_sentence'] = new_ex
                elif not pd.get('example_sentence'):
                    pd['example_sentence'] = clean_example(en)
                changed += 1
            else:
                # Not in our dict – leave a visible TODO so we can catch it
                pd['english'] = f'TODO: {pd.get("german", "?")} → {en[:40]}'
                changed += 1
        # Recurse into subtopics (not used in current data but safe)
        process_topics(t.get('subtopics', []))
        kept.append(t)
    return changed, removed

def fix_file(path):
    with open(path, encoding='utf-8') as f:
        data = json.load(f)
    total_changed = total_removed = 0
    for domain in data.get('domains', []):
        c, r = process_topics(domain.get('topics', []))
        total_changed += c
        total_removed += r
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print(f'{path}: {total_changed} KPs fixed, {total_removed} KPs removed')

if __name__ == '__main__':
    root = os.path.join(os.path.dirname(__file__), '..', '..')
    for fname in ['trainer/data/levels/a1.json', 'trainer/data/levels/a2.json']:
        fix_file(os.path.join(root, fname))
